# Use an official Node.js runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install ONLY production dependencies
RUN npm install --omit=dev

# Bundle app source
COPY . .

# Your app binds to port 3000, but Heroku will map it to 80/443 automatically
EXPOSE 3000

# Define the command to run your app
CMD [ "node", "backend/server.js" ]